### ISSUE TITLE
i2c slave mode gets stuck

### ISSUE THREAD

**Issue by mfiumara** [STMicroelectronics/STM32CubeL0#26] opened 2022-05-31 17:36 UTC
**Describe the set-up**
* I'm using a custom board with an STM32L031F4Px
* IDE is stm32Cube Version 1.9.0
* My compiler is gcc-arm-none-eabi-10.3-2021.10

**Describe the bug**
Trying to respond to a read request from a master (configuring the STM32 as slave device) as per https://st.force.com/community/s/article/how-to-create-an-i2c-slave-device-using-the-stm32cube-library. This simply does not work, the only way to get it to work kind of is to reset the I2C peripheral in the transfer complete callback, but this results in loss of data.

Not sure how this is supposed to work, I have enabled interrupts and they are being triggered, but the problem is my SCL line goes down and does not recover. The address is correctly matched but I can't get any further:

![image](https://user-images.githubusercontent.com/1368859/171239148-13eb500e-4822-4b70-9f47-5e1904f22b4c.png)

**How To Reproduce**
1. Set-up the project as per https://st.force.com/community/s/article/how-to-create-an-i2c-slave-device-using-the-stm32cube-library.
2. Use the latest version of this repo as the HAL
3. The problem must be somewhere in the stm32l0xx_hal_i2c.c file
5. Use case is I2C slave device

**Additional context**
I do not have any proposal for a patch, trying to figure out how to resolve it but I don't fully understand the slave HAL.

**Comment by mfiumara** [comment] 2022-06-03 09:09
I wrote my own driver by just pushing registers myself. It seems I get the same issue if I clear the TXIE register as stated in the example code in the STM32L0X1 reference manual.

I uncommented this out and now it seems to work. I can propose a change to the HAL for this fix if wanted.

**Comment by kjsdf7wr3** [comment] 2022-06-21 08:30
Is this related to https://github.com/STMicroelectronics/STM32CubeG0/issues/31 ?

**Comment by HBOSTM** [comment] 2022-06-30 16:05
Hello mfiumara,

Thank you for this report. The point you reported is actually related to the [How to create an I2C slave device using the STM32Cube Library](https://st.force.com/community/s/article/how-to-create-an-i2c-slave-device-using-the-stm32cube-library) article and not to the firmware published in this repository (may be a hardware pull-up is missing on I2C pins).
Unfortunately, we don't treat aspect related to articles in our GitHub repositories. They are rather treated at the [STM32-MCUs](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus) dedicated page of the ST Community .
Since this issue is not directly related to the STM32Cube firmware but rather to specific application (Aardvark module + STM32CubeMx + article), please allow me then to close this thread. 

Thank you for your comprehension.

With regards,
Houssine

**Comment by mfiumara** [comment] 2022-06-30 22:15
> Hello mfiumara,
> 
> 
> 
> Thank you for this report. The point you reported is actually related to the [How to create an I2C slave device using the STM32Cube Library](https://st.force.com/community/s/article/how-to-create-an-i2c-slave-device-using-the-stm32cube-library) article and not to the firmware published in this repository (may be a hardware pull-up is missing on I2C pins).
> 
> Unfortunately, we don't treat aspect related to articles in our GitHub repositories. They are rather treated at the [STM32-MCUs](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus) dedicated page of the ST Community .
> 
> Since this issue is not directly related to the STM32Cube firmware but rather to specific application (Aardvark module + STM32CubeMx + article), please allow me then to close this thread. 
> 
> 
> 
> Thank you for your comprehension.
> 
> 
> 
> With regards,
> 
> Houssine

Hi Houssine,

I am 100% sure that this is a bug in the HAL which I have now resolved by implementing the i2c slave mode myself following the stm32 0 series reference manual (writing registers directly).

I hope you can take this issue more seriously than just waving it off as an article inaccuracy or a hardware setup problem (pull up missing, really?). I would advise to leave this ticket open until it is actually resolved in case someone else spends weeks on figuring out what's going on in their implementation.

If you're low on resources I'd gladly help by sharing the basis of a working implementation.

Best regards,

Mattia

**Comment by etheory** [comment] 2022-07-05 15:10
@mfiumara I have been struggling for AGES with the G0 I2C implementation. I know 100% there is no issue with my hardware setup. What is happening is that the first HAL_I2C_Slave_Transmit_IT call works, and the second one never completes. It's definitely a bug with the HAL code itself, and all my attempts to report this issue have gone ignored by ST. If you have any tips about how to fix it I'd love to know, thanks!

**Comment by etheory** [comment] 2022-07-05 15:11
This also seems related potentially: https://github.com/STMicroelectronics/STM32CubeF4/issues/76

**Comment by HBOSTM** [comment] 2022-07-07 11:23
Hello @Mfiumara
We have followed the steps you have described to reproduce the issue and we did not get the same behavior you are having.  The salve is correctly responding as shown in the following results :

![image](https://user-images.githubusercontent.com/106234835/177756762-7d0ea9cc-ba6a-4e97-bbe3-fe8a913ee860.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/106234835/177755255-2b6152e6-a4a9-4da4-a37d-8ddc532ad5d2.png)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/106234835/177755298-776ab38c-fc78-41a0-b712-c3959bc948b9.png)



For a better analysis of the problem would you please provide us with the project you have used to reproduce the issue. Would you also confirm that you are using the latest version of the STM32CubeL0 (**V1.12.1**).

With regards,

**Comment by mfiumara** [comment] 2022-11-04 10:29
Hey as reported in the original ticket I used stm32Cube Version 1.9.0. I imagine it was fixed in the newer stm32cube release then?

**Closed** 2023-02-03 16:07 UTC
Labels: invalid, st community, Needs clarification
